### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1287723: character maps to <undefined>

### ISSUE THREAD

**Issue by gauravboss-code** [KamalDevelopers/Lynx#3]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1287723: character maps to <undefined> I HAVE GOT this please help

**Comment by DevGev** [comment]
In what function and file did the error occur? Did it happen when you started the program, or did some action trigger the error?
