### ISSUE TITLE
run.py on windows 11 fails

### ISSUE THREAD

**Issue by nmbazima** [KamalDevelopers/Lynx#4]
python .\run.py
Lynx Version 1.0.11ceddf
   INFO     {acceleratesupport.py:17} : No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
   INFO     {special.py:36} : Using NT-specific GLUT calls with exit callbacks
Traceback (most recent call last):
  File "C:\Users\pc\Lynx\lynx\main.py", line 89, in <module>
    utils.adblock.read_filter(confvar.BASE_PATH + "adblock/filter.txt")
  File "C:\Users\pc\Lynx\lynx\utils\adblock.py", line 36, in read_filter
    filter_set.add_filter_list(f.read())
  File "C:\Users\pc\miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1287723: character maps to <undefined>

**Comment by DevGev** [comment]
The adblock filter should be read in utf-8 format. Append argument `encoding='utf8'` in `open(path)` Line: 35, file: adblock.py
This should force the file be read in utf-8 format, instead of Windows cp1252 format.
